refresh_rate = 5

[appender.Root2]
kind = "console"
pattern = "%d - [%t] - %l - (%f:%L) - %m"

[appender.Root1]
kind = "file"
path = "root.log"
pattern = "%d [%t] %l %M:%m"

[appender.Prac]
kind = "file"
path = "prac.log"
pattern = "%d [%t] %l %M:%m"

[[appender.Root2.filter]]
kind = "threshold"
level = "info"

[[appender.Root1.filter]]
kind = "threshold"
level = "info"

[[appender.Prac.filter]]
kind = "threshold"
level = "debug"

[root]
level = "debug"
appenders = ["Root2", "Root1"]

[[logger]]
name = "prac"
level = "debug"
appenders = ["Prac"]
additive = true

[loggers."main"]
level = "info"
appenders = ["Root1"]
additive = true
