refresh_rate = "5 seconds"

[appenders.Root2]
kind = "console"
encoder = {pattern = '{d} - [{t}] - {l} - \({f}:{L}\) - {m}{n}'}

[[appenders.Root2.filters]]
kind = "threshold"
level = "info"

[appenders.Root1]
kind = "file"
path = "root.log"
encoder = {pattern = '{d} [{t}] {l} {M}:{m}{n}'}

[[appenders.Root1.filters]]
kind = "threshold"
level = "info"

[appenders.Prac]
kind = "file"
path = "prac.log"
encoder = {pattern = '{d} [{t}] {l} {M}:{m}{n}'}

[[appenders.Prac.filters]]
kind = "threshold"
level = "debug"

[root]
level = "debug"
appenders = ["Root2", "Root1"]

[loggers.prac]
level = "debug"
appenders = ["Prac"]
additive = true

[loggers."main"]
level = "info"
appenders = ["Root1"]
additive = true
